# Utilise l'image officielle Node.js alpine (léger)
FROM node:18-alpine

# Définit le répertoire de travail dans le container
WORKDIR /usr/src/app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances Node
RUN npm install

# Copie tout le code source dans le dossier de travail
COPY . .

# Expose le port 3000
EXPOSE 3000

# Commande pour démarrer ton serveur Express
CMD ["node", "server.js"]
