# Utilise une image Node officielle légère
FROM node:20-alpine

# Crée le répertoire de travail dans le container
WORKDIR /usr/src/app

# Copie uniquement les fichiers nécessaires
COPY package*.json ./
RUN npm install

# Copie tout le reste du projet
COPY . .

# Expose le port utilisé par l'application
EXPOSE 5000

# Définit la commande pour lancer le serveur
CMD ["node", "server.js"]
