name: CI Pipeline

on:
  push:
    branches: [main, develop, feat/ci]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run ESLint
        run: npx eslint . --ext .js,.mjs,.cjs --fix
        working-directory: ./api

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run tests
        run: npm test -- --coverage
        working-directory: ./api
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          POSTGRES_HOST: localhost

<<<<<<< HEAD
  build:
    name: Build Docker Image
=======
  security:
    name: NPM Audit Security Scan
>>>>>>> 6034178 (Changemet CI)
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
=======
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: ./api
    allow_failure: true  # ne bloque pas le pipeline si vulnérabilités faibles

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Jathushanselvarajah --password-stdin

      - name: Build and push Docker image
>>>>>>> 6034178 (Changemet CI)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.v1
<<<<<<< HEAD
          push: false
          tags: derniermetro-api:latest
=======
          push: true
          tags: |
            ghcr.io/Jathushanselvarajah/derniermetro-api:latest
            ghcr.io/Jathushanselvarajah/derniermetro-api:${{ github.sha }}
>>>>>>> 6034178 (Changemet CI)
